services:
  openresty:
    image: openresty/openresty:alpine
    ports:
      - "2006:80"
    environment:
      - DOMAINS=${DOMAINS}
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
    depends_on:
      - redis
    networks:
      - domainak-net

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    networks:
      - domainak-net

  test-app:
    image: nginxdemos/hello
    networks:
      - domainak-net

networks:
  domainak-net:
    driver: bridge

volumes:
  redis_data: