events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11;

    lua_shared_dict domain_cache 10m;

    server {
        listen 80;
        server_name _;

        location = /_track_visit {
            internal;
            proxy_pass http://backend:3000/api/stats/increment;
            proxy_set_header Host $host;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
        }

        location / {
            mirror /_track_visit;
            
            set $target_backend "";

            rewrite_by_lua_block {
                local host = ngx.var.host
                local cache = ngx.shared.domain_cache
                
                local cached_target = cache:get(host)
                if cached_target then
                    ngx.var.target_backend = cached_target
                    return
                end

                local redis = require "resty.redis"
                local red = redis:new()
                red:set_timeout(1000)
                
                local ok, err = red:connect("redis", 6379)
                if not ok then
                    return ngx.exit(500)
                end

                local res, err = red:get(host)
                
                if not res or res == ngx.null then
                    ngx.status = 404
                    ngx.say("Subdomain not registered.")
                    return ngx.exit(404)
                end

                cache:set(host, res, 30)
                ngx.var.target_backend = res
            }

            proxy_pass http://$target_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}